export enum UserStatus {
    COACH_WITH_TEAM = "COACH_WITH_TEAM",
    COACH_WITHOUT_TEAM = "COACH_WITHOUT_TEAM",
    ATHLETE_WITH_TEAM = "ATHLETE_WITH_TEAM",
    ATHLETE_WITHOUT_TEAM = "ATHLETE_WITHOUT_TEAM",
    ATHLETE_WITH_PENDING_TEAM = "ATHLETE_WITH_PENDING_TEAM",
}